### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ThomasAndersson1** [aalteirac/spotifySessionApp#2]
Hi,

I did see your demo on Qonnections and I liked it very much. Now I want to show it to my collegues but I don't have the knowledge how to install it on our server. I have tried to download and set up a virtual Proxy but I don't get it to work.

do you have a more step-by-step guide of how to install and configure it?

Br
Thomas

**Comment by aalteirac** [comment]
Hi Thomas, 

Thanks for your interest, I've change the project a bit to make it easier to play with Qlik Sense Desktop. You need to follow the readme and everything should be ok then. Let me know !

Thanks

**Comment by ThomasAndersson1** [comment]
Thanks, I have followed you instructions for desktop. But I have one more stupid question: How do I run it?

**Comment by aalteirac** [comment]
indeed better with "node run bin/www" and then go to http://localhost:3002 :-)

**Comment by ThomasAndersson1** [comment]
Now we are talking. I got the application running and connected to Spotify, but I receive this error

**Comment by ThomasAndersson1** [comment]
Spotify API has a rate limit, error could related (or not :-) ) : {"cookie":"X-sess=92d90292-46be-41b9-f3a9-befbff5ec05b; Path=/; HttpOnly; Secure"}

**Comment by aalteirac** [comment]
Do you have something printed in the node console, if so copy and paste here ?
What is the desktop version ?

**Comment by ThomasAndersson1** [comment]
First I didn't have any public playlist and then I added one.

Logged: thomas123andersson
{ error: 'no public playlist found, create one or turn an existing to public' }
Logged: thomas123andersson
Logged: thomas123andersson
Logged: thomas123andersson

**Comment by ThomasAndersson1** [comment]
should I restart the application? I have restarded the browser between my tries.

**Comment by aalteirac** [comment]
oki, seems you don't have any public playlist on your account. it's better to restart yes. So add one public playlist or turn one of yours into public and let me know. Thanks !

**Comment by ThomasAndersson1** [comment]
Hi, I have done that but I still get the same message

Spotify API has a rate limit, error could related (or not :-) ) : {"cookie":"X-sess=b662103f-1a1b-488f-c5f4-1c0c707a6a45; Path=/; HttpOnly; Secure"}

and the consol looks like this

> command@0.0.0 start C:\Users\tandersson\Documents\Qlik\Sense\Extensions\spotifySessionApp-master
> node ./bin/www

Logged: thomas123andersson

**Comment by aalteirac** [comment]
What's the Qlik Sense Desktop version ?

**Comment by ThomasAndersson1** [comment]
Qlik Sense Desktop 3.2 SR2 (10.18.3)

**Comment by aalteirac** [comment]
Damn, I've updated the readme, you need SR3, sorry for that

**Comment by ThomasAndersson1** [comment]
Sorry, I still doesnt work. I upraded to SR4 (hope that was ok). Restarted my computer but I get the same error.
Could I have missed anything in the configuration?

**Comment by aalteirac** [comment]
It's more my fault not having all necessary information ready so no worries :-) I'm gonna do a fresh install on a vm and track the necessary steps. Meanwhile, check if you added the url in the REDIRECT URI's list on spotify: http://localhost:3002/spotify-session-app.html

**Comment by ThomasAndersson1** [comment]
Yes, it is there. Thanks for all the support.

**Comment by aalteirac** [comment]
Ok, checkout the config.js, I have cleaned too much this morning 🥇 (why should we have test cases ? Perhaps for that...)
Hopefully it should be ok now ! Let me know :-)

**Comment by ThomasAndersson1** [comment]
IT IS WORKING NOW 🥇 
But only with Firefox. I have tried it with Chrome and IE10, but it doesn't work, then I tried Firefox and no problem.
Thank you very much for you help. It will be nice to show this to my colleagues tomorrow.

**Comment by aalteirac** [comment]
Hey glad to read that ! I've tested with chrome and IE Edge, works fine for me :-( 
What's your chrome version ?

**Comment by ThomasAndersson1** [comment]
It is working with Firefox and Edge. But not with IE 11 or Chrome
IE 11 Version 11.1198.14393.0
Chrome Version 58.0.3029.110 (64-bit)

**Comment by aalteirac** [comment]
weird, I've got the exact same Chrome version 58.0.3029.110 (64-bit), running SR4 and no problem...

**Comment by aalteirac** [comment]
Ok to close the issue ?

**Comment by ThomasAndersson1** [comment]
Yes and once again thank for the all your help.

**Comment by aalteirac** [comment]
Thank you Thomas, you have done the dirty testing for others !
